### PR TITLE
Template Repeater Widget

### PR DESCRIPTION
**Pull request by mattgibbs**
PyDMTemplateRepeater takes a .ui file with macro variables as a template, and a JSON file (or a list of dictionaries) with a list of values to use to fill in the macro variables, then creates a layout with one instance of the template for each item in the list.

See the new docs for more info.  Also includes tests.

### CODE REVIEW

**Comment by teddyrendahl** [comment]
One issue I have with these repetitive widget implementations is that you often end up tiling your a horizontal layout over and over again vertically. This works alright but often really what you want is a grid so that the first element of each tiled item lines up together. This involves breaking the layout and resetting them in a grid. Is this what the flow layout stuff is for? I couldn't quite follow what that did.

**Comment by mattgibbs** [comment]
@teddyrendahl Yeah, that is sort of an issue, and no, the flow layout doesn't fix that (it orders things like how text flows in a text box, where it wraps around to a new line when you reach the end of the current line).  In the template, if you want 'columns' to line up right you have to be pretty strict about setting their min/max width and scaling properties.  But I think that's a trade-off I'm willing to accept for this particular widget.  I don't want the Template Repeater to just be a way to make tables.

I *do* think making tables of sub-widgets is commonly-desired functionality though.  I have some ideas for a table-specific widget that would do this really nicely, with row/column headers, resizing of columns, etc.  Maybe I'll get to that sometime in the next couple of months...

**Comment by teddyrendahl** [comment]
Would certainly be interested. I also want to clarify (maybe I'm misunderstanding or not explaining well enough), even just to get something to line up nicely like below I need to use `QGridLayout` not a mix of `QHBoxLayout` and `QVBoxLayout`. Otherwise the `PyDMLineEdit` widgets all end up different size / horizontal positions based on the name of the attribute.

Screen Shot 2019-03-19 at 5 44 30 PM

**Comment by mattgibbs** [comment]
opsklys_pydm

Here's a somewhat ugly example of what the table-specific version might look like.  This is done in code though.  The hard part is making it something that works in Qt Designer.

**Pull request merged**
