### PR TITLE
MNT: move to using qtpy instead of own compatibility layer

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
@hhslepicka rebased.

Check the context manager changes around the mutex locking carefully.

**Comment by tacaswell** [comment]
The one failure is due to unexpected log levels, can someone point me in the right direction to fix that?

**Comment by hhslepicka** [comment]
Thank you for the rebase @tacaswell.
I will take a look at the errors today and add to the PR.

**Comment by tacaswell** [comment]
Gah!  Sorry I missed a bunch of the QtGui -> QtWidgets switches!

**Pull request merged**
