### PR TITLE
add polyline drawing widget

### LINKED ISSUE #578: PyDMDrawingPolyline widget
**What's the problem this feature will solve?**
PyDM needs a widget that draws a piecewise-linear line so that MEDM's [polyline](
https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html#Polyline) widget can be rendered.

Currently, there are no PyDM widgets to make this translation.  The closest approximation is to place *n-1* PyDMDrawingLine widgets in a PyDMFrame.

**Describe the solution you'd like**
The points of the line are specified and a straight line is drawn between each pair of points in the line.  It is not necessary for the first and last points to be connected.

**Additional context**

see the MEDM documentation: 
https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/MEDM/MEDM.html#Polyline

### PR DESCRIPTION
**Pull request by prjemian**
fixes #578 in support of translating MEDM's .adl screen files into PyDM's .ui file format

### CODE REVIEW

**Comment by prjemian** [comment]
needs:

* [ ] documentation
* [ ] unit tests
* [ ] graphical editor support for list of points
* [ ] review of the coordinate system used

Screens (.ui files) created with this widget have been created and displayed with *Qt designer* and *pydm* from this branch, respectively.  Included are screen shots and the test files displayed 
for both MEDM and PyDM.

[polyline-arrow.tar.gz](https://github.com/slaclab/pydm/files/3854562/polyline-arrow.tar.gz)

polyline

**Comment by prjemian** [comment]
Note, the `polyline-arrow.ui` was created from `polyline-arrow.adl` with the [*adl2pydm*](https://github.com/BCDA-APS/adl2pydm) translator!

**Comment by prjemian** [comment]
note: this MEDM configuration did not end up in the .ui file.  That's a bug in the adl2pydm, not a bug in the new widget, though.

```
	"dynamic attribute" {
		vis="if not zero"
		chan="PYDM:visible"
	}
```

**Comment by prjemian** [comment]
@hhslepicka , @mattgibbs : Seems as if #579 & #581 belong with this PR.  Agree?

**Comment by prjemian** [comment]
No comments so far.  Want to get this PR ready for review this week.  So many of the synApps screens use a polyline widget.  Way too much work to redesign all of them (by so many authors).

**Comment by prjemian** [comment]
no unit test failures from this widget

```
(pydm_prj) mintadmin@mint-vm:~/.../eclipse/pydm-prj$ pytest pydm/tests/widgets/test_drawing.py 
============================ test session starts ============================
platform linux -- Python 3.7.6, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
PyQt5 5.12.3 -- Qt runtime 5.12.5 -- Qt compiled 5.12.5
rootdir: /home/mintadmin/Documents/eclipse/pydm-prj
plugins: cov-2.8.1, timeout-1.3.4, qt-3.3.0
collected 144 items                                                         

pydm/tests/widgets/test_drawing.py .................................. [ 23%]
..................................................................... [ 71%]
.........................................                             [100%]

============================ 144 passed in 9.72s ============================
```

**Comment by prjemian** [comment]
Is a graphical editor for the list of points necessary?  At least for now, this is widget is for MEDM-compatibility.  I believe we can get by with the StringList editor for now.
2-point line

When there is a demand for a graphical editor, we'll need some drawing tools to support it.

**Comment by prjemian** [comment]
@hhslepicka , @mattgibbs : I believe that the PyDMDrawingPolyline widget (#578) is ready. 

Please check the coordinates of the set of points.  That's the last [punch list item](https://github.com/slaclab/pydm/pull/580#issuecomment-554662997).

#579 is not ready yet.  Perhaps for another PR?  (Note the PyDMDrawingIrregularPolygon widget is a special case of this PR where the first and last points are the same coordinates.  Thus it is a could be part of this or stand by itself after this is reviewed and merged.  I'd like the latter.)

**Comment by prjemian** [comment]
This PR is ready for review.  Can it be reviewed this week?

**Comment by hhslepicka** [comment]
@prjemian I will try. With all the curtailment going on a lot changed. If I can't get this reviewed this week it will be for the next one for sure.

**Comment by hhslepicka** [comment]
@prjemian,

Thank you for another great collaboration.

Here are some comments for discussion:

- Property Editor:
I think that the property is simple enough that we can get around with it being that way.
The error handling that you added and validations make it way better.

- Coordinate System:
Overall screen coordinates seems fine. For all the other widgets we use the widget relative coordinates as floats 0 - 1 and scale it up to the dimensions which causes a lot of confusion. I think we need to revisit some of the drawing widgets mainly in what encompass the rotation.
For the rotation what I tried to do is to calculate the largest rectangle that would fit in the rotated coordinates and draw using that as boundaries. Needless to say that it causes distortions.
I vote for keeping this one as screen coordinates as it will be more intuitive for users. What do you say, @klauer and @mgibbs?

- Irregular Polyline:
Is the difference only the fact that the initial point must be the same as the last?
Should we have a property here like "closed" which would set an additional point being the last one?

- Fill
How do we feel about that? (Pun intended :neckbeard: ) 
Should we assume fill and use the brush in case it is "closed" ?

**Comment by klauer** [comment]
Intuitive coordinates are the best coordinates. Those can always be converted to convenient normalized values internally.

Is there any way that scaling of lines could be done correctly when the container widget resizes, or is it always stuck to the original positions?

**Comment by hhslepicka** [comment]
@klauer since we are talk about screen coordinates there should be no scaling otherwise (100, 100) is no longer the true.

**Comment by hhslepicka** [comment]
Rebased on top of master.

**Pull request merged**
