### PR TITLE
PyQt5 Support

### PR DESCRIPTION
**Pull request by gabrielfedel**
New pull request with changes to support PyQt5.
Now I've tested and it's ready to use.

### CODE REVIEW

**Comment by mattgibbs** [comment]
Thanks Gabriel, I'll start taking a look.

**Comment by mattgibbs** [comment]
Hi Gabriel, just wanted to let you know I haven't forgotten about this - I ran into some issues while merging and testing, and ended up deciding to make some modifications so that it is easier to force pyqt4 mode even if pyqt5 is available.  So it is taking a little longer than just a merge.  Stay tuned!

**Comment by gabrielfedel** [comment]
Hello Matt, Great!

Let me know if I can help.

Thank you!

**Comment by mattgibbs** [comment]
OK, I have a new branch that I'd like you to try out, called 'pyqt5-compat' (https://github.com/slaclab/pydm/tree/pyqt5-compat)

For me, it seems to work pretty well.  Implementing this was really good, it forced me to fix a lot of issues with the way things get imported.  A consequence: If you want to use designer plugins, you'll have to change the PYQTDESIGNERPATH from pydm/widgets to just pydm/

If it works for you, I'll merge it in.

**Comment by gabrielfedel** [comment]
Great!

I'll try it (I start trying, but i have problem with PyQt5.QtDesigner on RHEL. I will make tests on Debian and return to you soon).

Thank you.

**Comment by gabrielfedel** [comment]
Hello Matt, 
I didn't forget this. I testing and finding some small problems. I trying to fix this problems on my new fork.
Do you want that I open an issue for problems I find?

**Comment by mattgibbs** [comment]
Its up to you - if you make issues, I'll work on fixing them, but if you would rather fix them yourself than wait for me, probably no need to make an issue.

**Comment by mattgibbs** [comment]
Hi Gabriel, I'm going to go ahead and pull the pyqt5-compat branch into master, I've been using it quite a bit in both pyqt4 and 5, and it seems to work well for me.  We can fix any issues you run into on the master branch.

**Comment by mattgibbs** [comment]
Closed, implemented PyQt5 compatibility in v0.1.1.

**Pull request closed without merging**
