### PR TITLE
WIP: Merge Latest from Master into 2.0 - Brace Brace...

### PR DESCRIPTION
**Pull request by hhslepicka**
At the end it was not so bad...
Tests are passing locally... Let's see with the new CI matrix...

Also testing applications here locally to ensure that all seems fine.

### CODE REVIEW

**Comment by klauer** [comment]
❤️ 2.0.... I'll need some time for this one...

**Comment by hhslepicka** [comment]
Me too... I am seeing some issues with the connection of channels... soon to be solved!

**Comment by hhslepicka** [comment]
Ok... my issue was my dead-old EPICS Base that I had locally along with its caRepeater.

**Comment by klauer** [comment]
Think we should just merge and work out issues as we go? If so, anything to preemptively add github issues for?

**Pull request closed without merging**
