### PR TITLE
PyQt5 Compatible

### PR DESCRIPTION
**Pull request by gabrielfedel**
Hello,

I made changes on code to be compatible with PyQt5. For this I try the import for pyqt5 first, if doesn't work, import PyQt4. I have to create new ui files generated from pyuic5. I made some tests, and apparently everything is ok.

### CODE REVIEW

**Comment by mattgibbs** [comment]
@gabrielfedel, thank you very much!  At first glance these seem like great changes.  I'll start reviewing this in detail and hopefully merge it in soon - I have a bunch of other changes from a non-github contributor that I need to merge also, so it might take a little while.

**Comment by gabrielfedel** [comment]
Hello Matt! Thank you!
I didn't tested the widgets with Qt-Designer 4 (only with 5), so I will try it on this week.

**Comment by gabrielfedel** [comment]
Hello again Matt,
we find some bugs on this branch, so I will close this pull request, and when we fix I made a new, ok?

**Comment by mattgibbs** [comment]
Sounds good!  I'll keep watching.

**Pull request closed without merging**
