### PR TITLE
ENH: Rpc support

### PR DESCRIPTION
**Pull request by nstelter-slac**
Add support for RPC using p4p extension (https://mdavidsaver.github.io/p4p/rpc.html).

More context here: https://github.com/slaclab/pydm/issues/1035

Could expand to have RPC address editor in designer

### CODE REVIEW

**Comment by nstelter-slac** [comment]
https://mdavidsaver.github.io/p4p/client.html#p4p.client.thread.Context.rpc

**Comment by nstelter-slac** [comment]
to test real PV:

cd examples/rpc
pydm rpc_labels.ui
->open in designer and modify one of the labels to have address:
pva://KLYS:LI12:11:ATTN_CUR&

can also try it with polling:
pva://KLYS:LI12:11:ATTN_CUR&pydm_pollrate=3.0

**Review by jbellister-slac — COMMENTED** [review]
This is great, thanks! Examples well-explained and work fine, connecting to live data works fine, tests look good.

**Review by YektaY — COMMENTED** [review]
Looks good and worked for me

**Pull request merged**
