### PR TITLE
ENH: PyDMTerminator widget

### LINKED ISSUE #150: Automatically close idle screens
Zelazny: Can I get a non-default option to close idle screens after a given number of minutes (like the SCP has)?  That way I don't have 100 non-important screens open forever buried where I'll never see or want them again?

By "idle" I mean so-many minutes have passed since the last button push.

### PR DESCRIPTION
**Pull request by hhslepicka**
A widget that I started prototyping a long time ago and today I felt like finishing it...
It was motivated by #150 as a way to automatically close an idle screen after a period of time.

Screen Recording 2021-02-26 at 6 18 05 PM

Input is welcome @klauer @ZLLentz @jacquelinegarrahan 

Closes #150

### CODE REVIEW

**Comment by ZLLentz** [comment]
This is pretty neat! Some of our old pyqt apps have this feature, so it's very welcome to see in a standard widget. Two thoughts:
- Typically you'd set this up on order hours, e.g. close the screen after 8 hours of no activity. So I'm not sure seconds is the best unit to use, but it's probably ok and most flexible.
- It'd be helpful if there was a built-in text display with a periodically updating timer, accurate to the highest relevant unit between hours/minutes/seconds, e.g.:
"This screen will close in 2 hours"
"1 hour"
"59 minutes"
"58 minutes"
...
"2 minutes"
"1 minute"
"59 seconds"

**Comment by klauer** [comment]
Neat 👍 Could be useful

**Comment by hhslepicka** [comment]
I went with seconds as more flexible... I understand the pain of writing 28800 for 8 hours...
The idea of displaying it as a label is good! I will modify that to be a visible widget by default with the proper text.
Thanks a lot for the input.

**Review by mattgibbs — APPROVED** [review]
Looks good!  Great name, btw.

**Comment by jacquelinegarrahan** [comment]
@hhslepicka could you imagine any cases where this would work along autosave of stored inputs?

**Comment by hhslepicka** [comment]
@jacquelinegarrahan it could be an use-case... maybe I can add a signal that is fired before closing the window.
That would allow a user to take care of saving what is needed.

**Comment by hhslepicka** [comment]
@ZLLentz I modified the code to make sure that it now shows a message properly on the screen with decreasing time.
Screen Recording 2021-03-02 at 3 38 43 PM

An example with timeout of `90065`:
image

I also fixed an issue that it would only grab interactions with the current window and not the whole application or keyboard key press events.

This widget now also has an icon at Qt Designer. In the process of getting this done I also fixed the Qt Designer interaction with icons which was broken.
image

**Comment by ZLLentz** [comment]
I like it :+1:
I suspect people will want to configure the granularity of the termination message (e.g. not wanting to see seconds/minutes ever), but other than that I've got nothing else to add.

**Comment by hhslepicka** [comment]
@ZLLentz thanks for the feedback...
For now it only shows the seconds if we are on the last minute... I should probably do the same for the remaining items...
Do you think it is a good idea?
E.g.: If we have days, only show hours on the last day... if we have hours, only show minutes on the last hour... etc...

**Comment by ZLLentz** [comment]
I think that sort of behavior is appropriate and will probably be what the user wants to see 95% of the time

**Pull request merged**
