### PR TITLE
New Navigation Bar

### LINKED ISSUE #105: Toggle Navigator Visible / Invisible
The navigator definitely needs to be something that can be toggled.
@mattgibbs

### PR DESCRIPTION
**Pull request by mattgibbs**
This adds a new, QToolBar-based navigation bar to replace the old one.  The new nav bar is hide-able, and provides QActions for all items.  These actions have hotkeys, and live in the menus as well.  I removed the search/address bar for now, since there is no search functionality yet, and manually typing in the full path to a display is crazy (that is much better handled by the open file dialog).

To make icons for the toolbar buttons, I've included the Font Awesome icon font in the project, and built a small utility class to create QIcons from characters in the font.  There are a huge amount of icons in the font, these might be useful elsewhere in the project, and inside Display classes that users write.

This will close #105.

### CODE REVIEW

**Comment by hhslepicka** [comment]
@mattgibbs Awesome improvement! It looks really nice!
In a quick test here I noticed that some of the examples are being collapsed... is it the case that this change removed that fix to not collapse the screen to a very small size?

Do we need to install the font and the json file that are now at pydm/utilities/fontawesome* ? If we do, we will need to include a line at the MANIFEST.in in order to have it copied with PyDM's code in the same way as the *.pkl files in that folder!

Is it possible to add an option to open PyDM with the navigation bar hidden? Maybe something on the launcher? `--no-nav-bar `

Other than that, really awesome and looking great! 👍

**Comment by mattgibbs** [comment]
Hi @hhslepicka, I just added a couple commits to add a command line flag to hide the navbar, and set a minimum width on the window.  Nice ideas!  Have you had a chance to look into the MANIFEST.in stuff?

**Comment by hhslepicka** [comment]
Hi @mattgibbs, thank you for the new features added.
Yes... we will totally need to add the following line to MANIFEST.in:
```
include include pydm/utilities/fontawesome*
```
This line makes it necessary: https://github.com/mattgibbs/pydm/blob/70980764dadac517381d87d3e2ea42628b02f45b/pydm/utilities/iconfont.py#L25

As soon as you send this modification I will merge it in.

**Comment by mattgibbs** [comment]
@hhslepicka Added!  Hopefully this does the trick.

**Comment by hhslepicka** [comment]
Awesome thank you @mattgibbs

**Pull request merged**
