### PR TITLE
Shine epics7

### PR DESCRIPTION
**Pull request by lvhuihui1988**
Make the widgets to support EPICS V7/pva protocol.

### CODE REVIEW

**Comment by jbellister-slac** [comment]
Hi @lvhuihui1988, EPICS 7/pva supports was added in the v1.16.0 release, using the P4P package:

https://slaclab.github.io/pydm/data_plugins/p4p_plugin.html
https://mdavidsaver.github.io/p4p/

Installing P4P into the same environment as PyDM should cause any channels specified with the `pva://` protocol to use that plugin.

If a different python pva wrapper would be preferred, that should be specified here as to ensure that changing the pva plugin does not also affect the channel access one:

https://github.com/slaclab/pydm/blob/master/pydm/data_plugins/pva_plugin.py

So an option could be made for caproto there. However, I think some changes would need to be made to the PyDM caproto data plugin first in order to fully support EPICS 7. Were you successful in using caproto with PyDM this way?

**Comment by prjemian** [comment]
Can you outline or describe what work is involved to support pvapy?  https://github.com/slaclab/pydm/blob/1dd59b9d8a700926c774ca27e522e843a5302164/pydm/data_plugins/pva_plugin.py#L12-L14

**Comment by prjemian** [comment]
> So an option could be made for caproto there. However, I think some changes would need to be made to the PyDM caproto data plugin first in order to fully support EPICS 7. Were you successful in using caproto with PyDM and pvAccess this way?

By _fully_, you mean caproto would need to fully support both CA **& PVA** protocols in EPICS 7.  It (caproto) only supports CA, as its name provides.

**Comment by jbellister-slac** [comment]
> By _fully_, you mean caproto would need to fully support both CA **& PVA** protocols in EPICS 7. It (caproto) only supports CA, as its name provides.

I did see that some pva support had been started with caproto when looking at this, but I haven't tried it out myself yet and not sure how much further work is needed

https://caproto.github.io/caproto/v0.8.1/pva/index.html

**Comment by jbellister-slac** [comment]
> Can you outline or describe what work is involved to support pvapy?
> 

It would require writing a new data plugin similar to the p4p one:

https://github.com/slaclab/pydm/blob/master/pydm/data_plugins/epics_plugins/p4p_plugin_component.py

Then `pva://` requests could be routed to the `pvapy` plugin instead

**Comment by klauer** [comment]
PVA support has been removed from caproto as in the master branch. 

Why? Well, there were zero reported uses of it in the wild in the first year that it was released, I couldn't even get anyone to try it when I specifically asked them, and now - I'm afraid I just don't have the time to maintain it.

**Comment by mattgibbs** [comment]
@prjemian Adding pvapy support probably isn't too tough to add.  Somebody would need to write another data plugin, analogous to the p4p one: https://github.com/slaclab/pydm/blob/master/pydm/data_plugins/epics_plugins/p4p_plugin_component.py

**Comment by mattgibbs** [comment]
@lvhuihui1988 Let us know if the new pva protocol support we've added works for you.

**Comment by lvhuihui1988** [comment]
> Hi @lvhuihui1988, EPICS 7/pva supports was added in the v1.16.0 release, using the P4P package:
> 
> https://slaclab.github.io/pydm/data_plugins/p4p_plugin.html https://mdavidsaver.github.io/p4p/
> 
> Installing P4P into the same environment as PyDM should cause any channels specified with the `pva://` protocol to use that plugin.
> 
> If a different python pva wrapper would be preferred, that should be specified here as to ensure that changing the pva plugin does not also affect the channel access one:
> 
> https://github.com/slaclab/pydm/blob/master/pydm/data_plugins/pva_plugin.py
> 
> So an option could be made for caproto there. However, I think some changes would need to be made to the PyDM caproto data plugin first in order to fully support EPICS 7. Were you successful in using caproto with PyDM and pvAccess this way?



> Hi @lvhuihui1988, EPICS 7/pva supports was added in the v1.16.0 release, using the P4P package:
> 
> https://slaclab.github.io/pydm/data_plugins/p4p_plugin.html https://mdavidsaver.github.io/p4p/
> 
> Installing P4P into the same environment as PyDM should cause any channels specified with the `pva://` protocol to use that plugin.
> 
> If a different python pva wrapper would be preferred, that should be specified here as to ensure that changing the pva plugin does not also affect the channel access one:
> 
> https://github.com/slaclab/pydm/blob/master/pydm/data_plugins/pva_plugin.py
> 
> So an option could be made for caproto there. However, I think some changes would need to be made to the PyDM caproto data plugin first in order to fully support EPICS 7. Were you successful in using caproto with PyDM and pvAccess this way?

Thanks, @jbellister-slac, I have installed P4P and now it can use pva protocol. Thanks again.

**Comment by jbellister-slac** [comment]
Excellent, thanks for confirming! I will close this one for now then. But please do let us know if you run into any issues using the pva plugin that we could help with.

**Pull request closed without merging**
