### PR TITLE
Pr enhancement of PyDMWaveformTable

### PR DESCRIPTION
**Pull request by fernandohds564**
I've done some enhancements on the widget PyDMWaveformTable:

 - The number of columns can be larger than one. Useful to display an array that represents matrices or to display the array horizontally.

- Now it is possible to select the labels of the Headers of each row and column in QtDesigner.

 - It is also possible to select the flags to be applied to the Table items in QtDesigner.

### CODE REVIEW

**Comment by mattgibbs** [comment]
Crap!  I stupidly merged this with my master branch, then pushed it to your PR branch.  I'm going to try to clean it up but I may end up opening a new PR for this.

**Comment by fernandohds564** [comment]
@mattgibbs If you want I can close this PR and open another one. I could even remove the `flagItems` property, because the way you handled the write access in your last commit is better than what I had done. I think this property is not necessary anymore.

**Comment by mattgibbs** [comment]
Leave this open, I think I can fix it.  Good idea removing flagItems, I'll go ahead and do that too.

**Comment by mattgibbs** [comment]
I had to merge via a new PR after all (#147).  Thank you again @fernandohds564.

**Comment by fernandohds564** [comment]
Thank you, @mattgibbs !

**Pull request closed without merging**
