### PR TITLE
ENH: add "basic settings" dialog for all PyDM widgets in the designer

### PR DESCRIPTION
**Pull request by klauer**
Though this works to the extent that I needed it for, I am passing this along to PyDM devs to clean it up and tailor it for general usage. It should be pretty easy to extend for other data types (colors, etc.). @YektaY @jbellister-slac feel free to either push to this branch or make a new PR based on my commits. Or if you like it enough as-is, you could also merge and iterate on it from there. I don't mind either way.

With the contents of this PR, double-clicking on a PyDMByteIndicator gives:
image

or an embedded display:
image

Right-clicking on channel-holding widgets gives:
image

### CODE REVIEW

**Comment by mattgibbs** [comment]
This is crazy, I was making a panel today and started daydreaming of almost this _exact_ idea.

**Comment by slactasha** [comment]
I think this sort of improvement will make a lot of people really happy!

**Comment by klauer** [comment]
OK, so:
* It's been close to 3 months since this PR was opened
* In order for this to be considered as a project for the EPICS Codeathon 2022, there needs to be some actionable feedback from the repository maintainers
* To that end - has anyone actually tried this?

Alternate options:
* This has been in decent working order since the PR was opened. You could consider giving it to PyDM users now. It's a vast improvement over the status quo, in my opinion. Merging, tagging, and making your decisions as to how to improve it could come later.
* If it's not in line with what you want to do in PyDM, it should be closed.

**Comment by jbellister-slac** [comment]
The idea behind this as a codeathon project was someone (especially if they create displays regularly as part of their workflow) might like to grab this branch and take it for a spin and suggest/work on any improvements they could think of. But this might be too open-ended, or risks them just being happy with it as is and then having to move onto something else. So maybe it's best to not include it.

But we have given the feature a try and do really like all the functionality there. And regardless of whether or not this gets worked on during the codeathon it is slated to go into the next release after a round of testing and review of the code.

**Comment by klauer** [comment]
> The idea behind this as a codeathon project was someone (especially if they create displays regularly as part of their workflow) might like to grab this branch and take it for a spin and suggest/work on any improvements they could think of. But this might be too open-ended, or risks them just being happy with it as is and then having to move onto something else. So maybe it's best to not include it.

Open-ended can be OK, I think. That being said, I'm not sure of the background of the majority of our attendees to say whether or not they regularly make PyDM screens. If you can find even one or two things that could/should be added once we get started at the codeathon, it would definitely make this an obvious choice to target, project-wise.

Also, please feel free to let me know if there's anything else on your mind for projects that could use attention. It doesn't necessarily have to be PyDM - but it should at least be Python + EPICS adjacent/related.

> But we have given the feature a try and do really like all the functionality there. And regardless of whether or not this gets worked on during the codeathon it is slated to go into the next release after a round of testing and review of the code.

Got it. Thanks for clarifying!

**Comment by ZLLentz** [comment]
I'm going to take this for a spin! If everything looks good, maybe we should merge as a good improvement and revisit in follow-up pull requests?

The automated test failure seems unrelated to the PR- the whole test build freezes during the start on windows?

**Comment by prjemian** [comment]
I love this idea!

**Review by ZLLentz — APPROVED** [review]
Overall I wish I already had this in my prod pydm :+1:

There are minor sizing/spacing issues and some of the widgets would benefit from additional fields in the dialog- but I don't think these are things that should hold up this PR. We can address those individually on an ongoing basis.

Some of the more subtle stuff like the channel copy/paste support is especially good.

No tests here- it's hard to imagine the proper way to test it though.

Perhaps individual pydm widgets should have some way to define/extend their own basic settings dialog? That way the widget designer can have more control over how their widget is interacted with in the designer.

**Review by jbellister-slac — APPROVED** [review]
Agreed, let's go ahead and get this in the next release!

**Comment by ZLLentz** [comment]
@klauer after the last update you did to bring over the improved clipboard support, azure is throwing a fit
```
Fatal Python error: Aborted
```

**Comment by ZLLentz** [comment]
Locally (win10) things are a bit wonky, I have two widgets that disagree about the clipboard contents and neither of which show me what I'm going to copy:
image
image

**Comment by ZLLentz** [comment]
Status is:
- Linux builds broken on all PRs (?)
- Win/Mac failing here on test cases
- Win passes locally

I'm going to put a little bit of time into tweaking the clipboard settings here for windows because I have a windows and Ken does not

**Comment by ZLLentz** [comment]
Pre-merge plan:
- Fix issue where the Actions in the menu have stale text
- Understand and resolve the test failures unique to this PR

I'll focus on this for a bit

**Comment by ZLLentz** [comment]
Tests fixed ✔️ 
Let's get this in

**Pull request merged**
