### PR TITLE
PERF: reduce disk thrashing by performing macro substitutions in-memory

### PR DESCRIPTION
**Pull request by klauer**

### CODE REVIEW

**Comment by mattgibbs** [comment]
Hey Ken, great idea!  I'm mostly just waiting on good ol' appveyor to wake up out of its coma and test everything out.

Can you tell me what the change in pydm/widgets/base.py is for?  I am assuming some unrelated problem.

**Comment by hhslepicka** [comment]
@mattgibbs I asked for this change. The CI with new version of PyQt all of a sudden by a reason that I am not willing to look into started to deny access to the `channel` attribute of the `PyDMLineEdit` even though it was available... so to fix that and all the CI builds I asked Ken to include in his PR the fix that I found. Now all the tests are happy again.

**Comment by hhslepicka** [comment]
After this PR is merged I will rebase the others so we can kick the CI again and make sure that all is fine.

**Comment by hhslepicka** [comment]
No concurrent jobs sucks!
The price of free! :speak_no_evil:

**Comment by hhslepicka** [comment]
@mattgibbs let me know when you test it so we can merge in the changes.

**Pull request merged**
