### PR TITLE
Scale upgrade

### PR DESCRIPTION
**Pull request by laispc**
Hi,

This pull request implements some new properties for scale widget, such as orientation, inverted appearance, flip scale, tick color and bar indicator. Some small correction were done too.
The example file was adapted to show these new features. What do you think about them? :)

Thanks,
Laís

### CODE REVIEW

**Comment by laispc** [comment]
Okay, @hhslepicka , thank you for the comments! I am working on the topics you mentioned. :)

**Comment by laispc** [comment]
Hi. Everything is done. :)
I did not put docstrings for some of the QScale methods in cases where there were a correspondent method in QPyDMScaleIndicator. Is it okay?
Thanks!

**Comment by laispc** [comment]
Hi @mattgibbs. Thanks for the comment, I didn't realize that during my tests.
I also think that fixing one the bar width is a good idea. I'll add a commit with this feature, okay?

**Comment by laispc** [comment]
Hi. I added the property **scaleHeight** for setting the size of the fixed dimension of the bar.
How it works: when the bar is horizontal only its height is fixed, when the bar is vertical only its width is fixed.
I used the name "scaleHeight" instead of "scaleHeigth" because I take the **horizontally oriented bar** as reference.
The other dimension of the bar may resize freely, and can be restricted with properties inherited from QWidget if the user desires so.  
@mattgibbs, I don't know if my changes reflected what you had in mind. What do you thing about this? More suggestions are welcome.

**Comment by hhslepicka** [comment]
Hi @laispc ,

Thank you for fixing the index, it looks great now! 👍 
About the wiggle, I am still being able to reproduce it on my machine, I will try later at a Linux box to see if it is better. Are you able to simulate the same effect at your machine?
For that I used the scale and the slider examples so we can see better the effect.
I tried to record a GIF file but the FPS is not perfect... at least we can have an idea of what is happening.
pydm_scale

**Comment by laispc** [comment]
Hi, @hhslepicka. Thanks for the GIF, now it is easier to see the problem.
I did a similar test here (using the slider) on Linux, take a look in the attached GIF.
The only case I got the wiggle is when I go from positive to negative (or negative to positive). 
In any other case, the bar does not move.

scaler1

**Comment by laispc** [comment]
I tried to make both dimension of the bar fixed (width and height), but got the same effect.

The wiggle happens when the value label of vertical bar resizes to fit current value (it would happen with the horizontal one in other GUIs too). So I fixed the width of horizontal bar (in QtDesigner) and the wiggle disappeared for now.
scaler2

**Comment by laispc** [comment]
In the last GIF I posted, if one sets a very high number for value (using the edit), then a wiggle with happen again.

Maybe it is good to have the scaleHeight property and also let the user decides about fixing the width/height of the whole widget.

**Comment by klauer** [comment]
Any thoughts on making the value label for the vertically-oriented scale widget to be below the scale?

**Comment by laispc** [comment]
Hi, @klauer . This is a very good idea! I tried it and I liked the result (image attached). Makes the widget more compact.
I can try to make this change. What do you think, @hhslepicka ?

Btw, would it be interesting to have a property to set the value label above/below the scale?

scale_lower

**Comment by hhslepicka** [comment]
Hi @laispc! It would be great to have a property in which the user can choose the `value label` position (left, right, top, bottom).
Since doing this you will revisit the creation and drawing of the widget, there is another suggestion that if you think it is valid can be implemented too.

The idea is the following:
The widget behaves almost like the simple case with the indicator but it fills with color up or down. Here is a drawing to explain a bit what I am saying:
dcfd8f10-cb35-4815-bd38-bcb426f23921

**Comment by hhslepicka** [comment]
Hi @laispc, just pinging to see if you need some help or even if you will have the time to attack those last steps. Let me know so I can plan the work here or even merge the code as is and receive later the modifications.

**Comment by laispc** [comment]
Hi, @hhslepicka . I am currently working on value position feature. As soon as it is ready, I will start to implement the up-and-down fill. I believe I can deliver them during next week. In case I notice I won't make it, I will let you know.

Until then, I think the contents of this PR can be merged already if it is okay for you. I can submit these new features in another PR. What do think? Thank you!

**Comment by laispc** [comment]
Hi! I just pushed 3 new commits with the new properties we have discussed (value position and origin at zero).
I hope it is okay. :) Thanks.

**Comment by hhslepicka** [comment]
@mattgibbs would you mind to review this PR?

**Comment by mattgibbs** [comment]
@laispc sorry for taking soooooooooo long to review this.  It is really nice, thanks for putting up with all of my tiny criticisms.

**Pull request merged**
