### PR TITLE
ENH: Add the ability to display archiver data on time plots

### PR DESCRIPTION
**Pull request by jbellister-slac**
## Description
This PR will update the archiver appliance data plugin to support requests for historical PV data from PyDM widgets during runtime. The requests will be made asynchronously, with the data only returned when the request is complete via a signal, so there will be no performance impact on any running GUIs.

This plugin is different than the others in that it does not open a connection and then just constantly stream new data (which wouldn't make sense in the context of archive data). Instead it must be invoked via a signal for the time range of data requested. Keeping it as a plugin keeps it transparent to the widgets so that they can receive data from archiver the same way as any other data source.

A new type of time plot has been created, PyDMArchiverTimePlot, to display archived data. In order to keep things clean for users who do not have access to an instance of archiver appliance, this new widget will only be displayed if an environment variable for archiver appliance is set. These changes are also intended to be backwards compatible with all existing time plots, there should be no change in functionality to any such plots already created.

## Testing/Documentation
Several new unit tests were added for the new functionality for both the plot and the plugin itself. All existing tests pass, and existing examples run fine. Documentation for setting the archiver URL was added, along with the auto-generated documentation for the new type of plot.

Instructions for testing this PR:

export PYDM_ARCHIVER_URL=http://lcls-archapp.slac.stanford.edu
Use designer to create a new time plot with PV(s) that are archived setting the "Archive Data" column to true.
Run the plot. Drag the x-axis to the left to slowly get data from the archiver. Zoom out on the axis to get more data faster.

## Other notes
I've separated the archive data into its own data buffer. Initially I was just inserting it directly into the buffer of the time plot, but this way I think makes it more flexible for future improvements. The redraw was what I was worried about in terms of performance, but testing shows that it is not an issue with our buffer sizes. (If it is a concern in the future with much larger plot sizes, can re-visit and have a shared data buffer that only concatenates upon receiving new archive data)

The function for inserting data into the buffer (archiver_time_plot.insert_archive_data) is not used for now. The use case in the future could be for inserting raw data into the buffer when a user zooms into a section of the curve while maintaining the data around it. But such use-cases would be in a follow-up to this.

Python 2 support was dropped in the last release, so a couple Python 3 only features are used here. I can open a separate PR to remove the failing Python2 check.

## Screenshots

archive_editor

out2

### CODE REVIEW

**Review by ZLLentz — COMMENTED** [review]
Hi, sorry for the late review. Summary: code looks good, user experience was confusing, it's unclear if I was even looking at archived data.

Full notes from my review:
The code here looks clean and well-documented. I pointed out a few specific things that I especially liked and asked one question about maintainability.

I took this for a test run in a clean environment in python 3.9 with just pydm and its dependencies installed.
First, opening designer without the archive environment variable looked and worked as normal.

I ran `export PYDM_ARCHIVER_URL=http://pscaa01.slac.stanford.edu:17668` to try to use this to display data from the photon-side archiver from a photon-side host.

The first thing I notice is that I've lost access to the non-archiver timeplot in designer- the replacement clearly still has all the ca functionality, but since the name is `PyDMArchiverTimePlot`, it was confusing at first and I thought I had lost my ability to make normal time plots.

After playing around with it for a bit, I realize that I don't understand how to select my time range for the archiver data. I created two plots, one with the live PV and one with the archived PV, and I cannot tell any difference between them- both update constantly, both seem to be at about the same point in time, and both of them sit there accumulating new values. I would have expected the archiver plot to have a static view of the configured timespan, or something like that?

Is there some configuration step I'm missing here where the user can select a time range? E.g., "show me the last 6 hours" or something like that?

I verified that archiver queries for data to the URL I used work outside of pydm.

**Comment by slactasha** [comment]
Hi Zach,

Thank you for your detailed feedback and review comments. I can comment on the general intent and usability – the idea is that including archived data in the time plot is mostly transparent to the end user. Like the cs-studio databrowser, it simply backfills the displayed timespan with (typically optimized) requests from the archiver, then proceeds to acquire live data via channel access up to some live buffer value, so this part will look the same regardless of whether the data is archived. The only time it should be clear what’s live and what’s archived is if the archived data is reduced through deadbands. The user then does not need to specify a static time range to view, if they zoom out the archiver will submit a new request to fill in the range.

- Tasha

**Comment by ZLLentz** [comment]
Hi Tasha, thank you for that explanation. I think I must have been observing a bug or doing something wrong then, since zooming out my archiver plot did not result in any backfill, data was streaming in that looked identical to the live plot on the same display. I'll poke around with this some more and report back.

In general though, if everything is working properly, I should be able to set the timespan to, say, 3600 seconds if I want to display the last hour when the screen opens?

**Comment by jbellister-slac** [comment]
Hi Zach, thanks for trying this out and appreciate the feedback! Setting the timespan value will not currently work that way or have any effect, it is something I can look at adding.

One possible issue is make sure you are still using channel access for the archive plot instead of "archiver://" or anything like that. It will use channel access to connect to live data, while automatically converting to use archiver on the backend whenever you scroll left or zoom out on the plot.

If it still doesn't work, you can point me to where the plot you are testing is, and I can take a look.

**Comment by ZLLentz** [comment]
Ok, I see it working now, doing the same test as earlier. Perhaps I was having intermittent issues talking to my archiver, perhaps there was some other sort of user error?

I did go through and resolve several user mistake layers prior to stopping earlier, I'm not sure how many of these deserve a documentation call-out:
- setting up my python environment incorrectly
- picking the wrong archiver URL
- invoking the archiver:// plugin directly (and misspelling it as archive://, without the r)
- being on mouse mode = 1 button, instead of mouse mode = 3 button (is there a way to configure the default here? perhaps some pyqtgraph configuration?)

But now I can scroll, pan, and see recent archiver data with no issues.

I think this works exactly as advertised on the photon-side archiver: live data streams in using channel access, historical data is populated using archiver requests as needed. In that regard, it looks great!

I do think there is some missing demand gaps here where people will want to have displays that open up to "the last 6 hours" of a PV, or something to that effect. It's certainly not easy to use this tool to find a specific date range, but I don't think that's the intent, so I'm not worried about that. But if a user wants to have a permanent plot of "the last one hour of the photon energy" then that's something we may want to support in a future release.

One (bug? oddity?) that I see after typing all of that out: once the live update runs out of buffer points, it creates a data gap in the chart. So now I have a region of my plot at the original boundary between live and archived data that contains no data points. Pic attached, I'm not exactly sure how to handle this for the hybrid live/archive plot (or if it even needs to be handled)
image

**Comment by jbellister-slac** [comment]
Thanks! I can certainly add some documentation to those points. 

The mouse mode default looks like it is purposely set to 1 in the base plot. I'm not sure why that was chosen as the default, but I could at least expose it as a property in designer at some point to let the user set it.

As for the data gap, upon zooming out it should fill in that gap with archive data (once the data has made it to the archiver). But I can discuss with everyone and see if there's a preferred solution.

**Review by YektaY — APPROVED** [review]
Looks great!

**Pull request merged**
