### PR TITLE
BUG: fix issue where designer doesn't load pydm widgets when pydm is installed from PyPI using pip

### PR DESCRIPTION
**Pull request by nstelter-slac**
When pydm is installed from PyPI using pip, you should be able to set the env variable PYQTDESIGNERPATH to pip pydm install location so designer can load the pydm widgets.

But for PYQTDESIGNERPATH to be used to load pydm widgets, it needs to point to a dir containing the pydm_designer_plugin.py file. This file was put in the pydm repo's root dir. But pip only copies to the install locations python-package dirs (dir contains \_\_init\_\_.py), which for pydm is the /pydm subfolder of the root dir (which didn't contain the pydm_designer_plugin.py file).

The solution is to place the plugin file in the <pydm_root_dir>/pydm subdir so pip can grab it.

Also make conda install cmd in doc pin pyqt version.

### CODE REVIEW

**Comment by nstelter-slac** [comment]
tested install as follows:

```
// install everything except pydm in conda env
conda create -n pydm-pydm_test_pip_fix python=3.8 pyqt=5.12.3 pip numpy scipy six psutil pyqtgraph -c conda-forge
// install pydm from local repo on this patch
pip install pydm/
// find pip install location of pydm and set PYQTDESIGNERPATH
pip show pydm
export PYQTDESIGNERPATH=/home/nstelter/miniconda3/envs/pydm_test_pip_fix/lib/python3.8/site-packages/pydm
// confirm plugin file is in correct location
ls $PYQTDESIGNERPATH/pydm_designer_plugin
// launch designer and confirm pydm widgets load
designer
```

**Comment by nstelter-slac** [comment]
seems like this shouldn't effect conda installs, since they create their own pydm_designer_plugin.py file:

https://github.com/slaclab/pydm/blob/master/conda-recipe/build.sh#L15

**Comment by YektaY** [comment]
This was the origin behind changing the installation guide to unpin pyqt: https://github.com/slaclab/pydm/pull/999
Do you think this is more clear then just leaving a note that they need to pin to an older version of pyqt to be able to use pydm widgets in designer?

**Comment by nstelter-slac** [comment]
ok agree now on having main listed conda cmd pinned to pyqt=5,

but what about adding an example cmd of pyqt=5.12.3 pinned in the 'warning' section: https://github.com/slaclab/pydm/pull/1132/files#diff-e285c1b9901cd202e89d9f37e3249a6fee524a65428895e1a45fd062cc0f9acaL29

- explicitly shows how to pin the version
- want to catch the eyes of anyone just skimming for the correct install cmd (this happened to me b4, copy and pasted conda cmd but forgot to add pin)

**Comment by jbellister-slac** [comment]
> acts to catch the eyes of anyone just skimming docs for the correct install cmd (this happened to me b4, copy and pasted conda cmd but forgot to add pin)

I think I actually prefer the pinned 5.12.3 version as the default command for that reason. Or at the very least the warning box appearing before the install command so the reader sees it first.

We can also remove the pin of python to 3.8 there as it should work at least from 3.7-3.10, and should be handled by our conda recipe anyway. Should update that recipe during the next release to ensure it is correct.

**Comment by nstelter-slac** [comment]
ok moved the warning box above the normal cmd, but normal cmd has no pyqt pin. imo this is best of both worlds.

**Comment by nstelter-slac** [comment]
@jbellister-slac for the python pin, should we pin 3.7-3.10? or think we should list most recent python (3.12)?
if so, maybe we should add automated test running on 3.12?

 also in what way should conda recipe be updated? no python version is pinned there atm

**Review by jbellister-slac — APPROVED** [review]
Oh I was looking over on conda forge: 

https://github.com/conda-forge/pydm-feedstock/blob/main/recipe/meta.yaml

But yeah should update the version you were looking at first so they stay in sync, didn't realize there was no python version here. We could probably put a lower bound of at least 3.8 since even 3.7 has been end of life for a while now.

Running the tests against newer python versions also sounds good, but both of these things can be part of a different PR.

**Pull request merged**
