### PR TITLE
ENH: Add propertry for setting Qt Standard Icons in designer

### PR DESCRIPTION
**Pull request by nstelter-slac**
allow qt standard icons to be set in designer by exposing a custom property that sets the icon using python inside the property's setter.

this should provide a set of default icons cross-platform, since they ship with qt.

### CODE REVIEW

**Comment by nstelter-slac** [comment]
to test:

-pydm examples/shell_command/shell_command.ui
-click on shell command button
-copy any of the [Qt Standard Icons](https://www.pythonguis.com/faq/are-there-any-built-in-qicons/#:~:text=Qt%20ships%20with%20a%20small,standardIcon(name)%20), and set as the button's standardIcon property.

**Comment by klauer** [comment]
Neat! Could this be extended to support the fontawesome stuff built into PyDM as well - `pydm.utilities.iconfont`? https://github.com/slaclab/pydm/blob/master/pydm/utilities/iconfont.py#L1

**Comment by nstelter-slac** [comment]
can demo using Qt's standard and Font Awesome icons with: 

pydm examples/icons/icons.ui

**Review by jbellister-slac — APPROVED** [review]
Created a new display, worked exactly like I'd expect in both right hand window and basic settings editor in designer. Links for the valid icon names for both sets are good, example is helpful, and tests look good too. Thanks!

**Pull request merged**
