### PR TITLE
Scale indicator

### PR DESCRIPTION
**Pull request by laispc**
Hi,

Recently I needed a widget equivalent to the one described in issue #39 . So I started to write a class for it.
I tried to keep it simple. By now, a graphical pointer is drawn to indicate channel current value, but it is possible to add the option to draw a bar instead in the future.

Possible improvements:
- implement change of orientation
- indicator type option (pointer or bar)

Thanks,
Laís

### CODE REVIEW

**Comment by laispc** [comment]
Obs: it is more interesting to run the example using a motor RBV (so its possible to seen the pointer actually moving according to the motor movement).

As I did not find such PV type in pydm example IOC, I replaced channel property value with the VAL of positioner example motor.

**Comment by hhslepicka** [comment]
Hi @laispc thank you for this new widget! 
I have a couple of comments so far that you can address while I test it...

- [ ] Alarm handling is not working... You can try to test for instance with MTEST:Float and tweak its value outside to simulate the alarms. If you change the widget to inherit form QFrame & PyDMWidget you will get it for "free". Note: See PyDMEnumComboBox.

- [ ] Please use 4 spaces instead of Tab. 

The widget overall is a really nice addition. I will test more as soon as you send the changes.

**Comment by laispc** [comment]
@hhslepicka , thank you very much! I am working on the review topics. :)

**Comment by laispc** [comment]
Done. ;)

**Comment by hhslepicka** [comment]
Merged! Thank you @laispc !

**Comment by laispc** [comment]
Thank you, @hhslepicka ! :D

**Pull request merged**
