### PR TITLE
ENH: NTTables readable using label and byte indicator

### PR DESCRIPTION
**Pull request by jakerudolph**
Check out this branch implementing reading of NTTables, and let me know what you think. A couple of notes:

- column/row indices are appended to the PV name with parentheses, with format (label=column_name, column_with_element=element_to_match)
- While an arbitrary table can now be emitted by a signal, only PyDMLabel and PyDMByteIndicator widgets have been edited to be able to ingest and display values in an NTTable
- I understand if you would rather wait until a more holistic NTTable implementation is completed. Let me know, as this is useful for an application I'm working on, so I want to get a sense of when I'll be able to use it in production (on the scale of weeks, months, years).

Thanks!

### CODE REVIEW

**Comment by jbellister-slac** [comment]
Thanks! We will take a look at this, next week most likely. The time frame for NTTable support being part of pydm should be weeks, the plan is to do a new pydm release later this month which will include it.

**Comment by jakerudolph** [comment]
Oh that's great. Hopefully this branch can be helpful in some way, but I reckon y'alls implementation will be much more thorough and all around better.

**Comment by mattgibbs** [comment]
I like the idea behind this (make it possible to drive existing PyDM widgets with values from PVAccess structures), but I think there's a slightly different approach at the data plugin level that will be more powerful, and enable _any_ widget to use fields from structures, without needing to modify every widget.

We could define a syntax for specifying subfields in a `pva://PVNAME` address.  I'd propose something like this:
`pva://PVNAME/subfield/sub_subfield`
(this assumes there are never `/`s in PV names, we'd have to verify that it is a safe choice)
The pva plugin's `Connection` class needs to store that subfield stuff for later use.  Then, whenever `Connection.send_new_value()` is called, the `Connection` instance uses the subfield stuff to try to access the subfield (or sub-subfield) from the new value.  If that subfield exists, and its value is one of the normally-supported PyDM data types (float, int, str, np.ndarray, bool), that subfield value gets emitted.  If that subfield does not exist, or it is not a normally-supported data type (probably because it is a struct itself), emit the signal indicating disconnection or something.

We'll have to think about how to handle the future where some PyDM widgets _can_ directly absorb entire structures too.  Perhaps if the value isn't a normally-supported PyDM data type, we emit a dict.  Most widgets will not have a slot that matches, so nothing will happen in that case.

The plugin might also have some 'smarts' about some of the normative types, like if you do `pva://PVNAME/column_name` on a NTTable, it gives you the column as an np.ndarray.  Or, if you do `pva://PVNAME/column_name/5` it gives you the value of  row 5 of the column.

**Comment by jbellister-slac** [comment]
This was completed as part of #984, both the new widget and allowing access to sub fields.

**Pull request closed without merging**
